# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from create5 import Ui_Form
from delete import Ui_Form_del
from Modify2 import Ui_Form_Modify
from PyQt5.QtGui import QIcon


class Ui_Form_main(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 469)
        Form.setStyleSheet("background-color: rgb(10, 10, 10);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 50, 500, 250))
        self.label.setPixmap(QtGui.QPixmap("samba2.png"))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 320, 121, 51))
        self.pushButton.setStyleSheet("background-color: rgb(204, 153, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 320, 131, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(204, 153, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(450, 320, 121, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(204, 153, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.pushButton_3.setObjectName("pushButton_3")
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Team:2 SambaShare UseCase"))
        #Form.setWindowTitle("Team:2 Samba Share UseCase")
        Form.setWindowIcon(QIcon('team2.png'))
        Form.setWindowOpacity(0.95)
        self.pushButton.setText(_translate("Form", "Create"))
        self.pushButton.clicked.connect(self.CallCreate)
        self.pushButton_2.setText(_translate("Form", "Delete"))
        self.pushButton_2.clicked.connect(self.CallDel)
        self.pushButton_3.setText(_translate("Form", "Modify"))
        self.pushButton_3.clicked.connect(self.CallModify)




    def CallCreate(self):
        
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form(self.Form)
        self.ui.setupUi(self.Form)
        self.Form.show()
        
    def CallDel(self):
        
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form_del(self.Form)
        self.ui.setupUi(self.Form)
        self.Form.show()
        #self.Form.close()
    def CallModify(self):
        
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form_Modify(self.Form)
        self.ui.setupUi(self.Form)
        self.Form.show()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form2 = QtWidgets.QWidget()
    ui2 = Ui_Form_main()
    ui2.setupUi(Form2)
    Form2.show()
    sys.exit(app.exec_())